### ISSUE TITLE
Performace issues

### ISSUE THREAD

**Issue by darkheadmaster132** [jbredwards/Fluidlogged-API#217] opened 2024-11-27 20:39 UTC
Performance just dies when near ocean especially with ocean mods like subaquatic and oceanic expanse, no idea why

edit: (didn't know that mod has config file) After changing fluidloggedFluidSpread to 0 and removing removeVerticalFluidloggedFluidSpread performance is good but maybe set these as default?

**Comment by jbredwards** [comment] 2024-11-30 15:57
This appears to be a duplicate of #182 and #206. If you don't think this is a duplicate, could you send a [spark profile](https://spark.lucko.me)?

> After changing fluidloggedFluidSpread to 0 and removing removeVerticalFluidloggedFluidSpread performance is good but maybe set these as default?

I'm rewriting the fluid flow logic entirely, so until I release v3.0.0, also disabling "fancyFluidEntityCollision" and installing some performance mods (like Nothirium and CensoredASM) should help.

**Closed as completed by jbredwards** 2024-11-30 15:57 UTC
Labels: bug
