### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by meteorOSS** [jbredwards/Fluidlogged-API#40] opened 2021-12-19 04:10 UTC
[11:50:55] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:901) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:770) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World$3
	at net.minecraft.world.World.func_190524_a(World.java:724) ~[amu.class:?]
	at net.minecraft.world.World.func_175685_c(World.java:652) ~[amu.class:?]
	at net.minecraft.world.World.func_175722_b(World.java:598) ~[amu.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:536) ~[amu.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:515) ~[amu.class:?]
	at net.minecraft.world.World.func_175656_a(World.java:580) ~[amu.class:?]
	at git.jbredwards.fluidlogged_api.asm.ASMHooks.flowInto(ASMHooks.java:492) ~[ASMHooks.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:148) ~[aqe.class:?]
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:680) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:660) ~[oo.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:321) ~[aqe.class:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:717) ~[axw.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:497) ~[amu.class:?]
	at net.minecraft.world.World.func_175656_a(World.java:580) ~[amu.class:?]
	at git.jbredwards.fluidlogged_api.asm.ASMHooks.flowInto(ASMHooks.java:492) ~[ASMHooks.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:148) ~[aqe.class:?]
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:680) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:660) ~[oo.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:321) ~[aqe.class:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:717) ~[axw.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:497) ~[amu.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:190) ~[aqe.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:143) ~[aqe.class:?]
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:680) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:660) ~[oo.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:321) ~[aqe.class:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:717) ~[axw.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:497) ~[amu.class:?]
	at net.minecraft.world.World.func_175656_a(World.java:580) ~[amu.class:?]
	at git.jbredwards.fluidlogged_api.asm.ASMHooks.flowInto(ASMHooks.java:492) ~[ASMHooks.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:148) ~[aqe.class:?]
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:680) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:660) ~[oo.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:321) ~[aqe.class:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:717) ~[axw.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:497) ~[amu.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:190) ~[aqe.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:143) ~[aqe.class:?]
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:680) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:660) ~[oo.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:321) ~[aqe.class:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:717) ~[axw.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:497) ~[amu.class:?]
	at net.minecraft.world.World.func_175656_a(World.java:580) ~[amu.class:?]
	at git.jbredwards.fluidlogged_api.asm.ASMHooks.flowInto(ASMHooks.java:492) ~[ASMHooks.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:148) ~[aqe.class:?]
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:680) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:660) ~[oo.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:321) ~[aqe.class:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:717) ~[axw.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:497) ~[amu.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:190) ~[aqe.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:143) ~[aqe.class:?]
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:680) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:660) ~[oo.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:321) ~[aqe.class:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:717) ~[axw.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:497) ~[amu.class:?]
	at net.minecraft.world.World.func_175656_a(World.java:580) ~[amu.class:?]
	at git.jbredwards.fluidlogged_api.asm.ASMHooks.flowInto(ASMHooks.java:492) ~[ASMHooks.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:148) ~[aqe.class:?]
	at net.minecraft.world.World.func_189507_a(World.java:3000) ~[amu.class:?]
	at net.minecraft.world.gen.feature.WorldGenLiquids.func_180709_b(WorldGenLiquids.java:88) ~[bat.class:?]
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:352) ~[ank.class:?]
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88) ~[ank.class:?]
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:226) ~[anh.class:?]
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:470) ~[aze.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.generator.NormalChunkGenerator.func_185931_b(NormalChunkGenerator.java:46) ~[NormalChunkGenerator.class:git-CatServer-1.12.2-26208f0]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1233) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.populateCB(Chunk.java:1212) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:165) ~[on.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) ~[ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:174) ~[ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:335) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:894) ~[MinecraftServer.class:?]
	... 4 more
[crash-2021-12-19_11.50.55-server.txt](https://github.com/jbredwards/Fluidlogged-API/files/7740307/crash-2021-12-19_11.50.55-server.txt)

**Comment by jbredwards** [comment] 2021-12-19 17:11
duplicate of #31

**Closed as completed by jbredwards** 2021-12-19 17:11 UTC
Labels: bug, duplicate
