### ISSUE TITLE
 the betweenlands Mod rendering error

### ISSUE THREAD

**Issue by 19300000** [jbredwards/Fluidlogged-API#219] opened 2024-12-02 11:13 UTC
Version 2.2.4 doesn't have this problem, but versions 2.2.5-2.2.7 have this problem
![QQ20241202-190918](https://github.com/user-attachments/assets/e920ca89-954a-4c58-9bf6-db02c4a74544)

**Comment by jbredwards** [comment] 2024-12-02 11:55
duplicate of #209

**Closed as completed by jbredwards** 2024-12-02 11:55 UTC
Labels: bug
