### ISSUE TITLE
[1.7+] Incompatibility with FutureMC

### ISSUE THREAD

**Issue by Luke616** [jbredwards/Fluidlogged-API#68] opened 2022-03-26 03:29 UTC
**Describe the bug**
Fluidlogged API is crashing on startup when installed alongside FutureMC. This is likely due to FutureMC's feature which lets their lantern blocks be waterlogged. Happens with Fluidlogged API versions 1.7 and up, bug does not occur with version 1.6.2

This issue occurs even when lantern blocks are blacklisted in the new Fluidlogged API configs, and when they are disabled in FutureMC's configs.

**To Reproduce**
1. Install Fluidlogged API version 1.7+
2. Install FutureMC (tested with ver 0.2.8)
3. Start up minecraft

**Logs**
[crash-2022-03-25_20.06.48-client.txt](https://github.com/jbredwards/Fluidlogged-API/files/8354599/crash-2022-03-25_20.06.48-client.txt)

Fluidlogged API contains the following:
```
"blacklist":[
    {"blockId":"futuremc:lantern"},
    {"blockId":"futuremc:soul_fire_lantern"}
	],
```

**Comment by jbredwards** [comment] 2022-03-26 03:33
duplicate of #50

**Closed as completed by jbredwards** 2022-03-26 03:33 UTC
Labels: bug

**Comment by Luke616** [comment] 2022-03-26 03:41
Thank you, apologies for the duplicate report
