### ISSUE TITLE
[possible bug] Streams mod odd water render?

### ISSUE THREAD

**Issue by Carvercarver1** [jbredwards/Fluidlogged-API#59] opened 2022-03-19 23:59 UTC
Normally, Streams mod has its water have a movement animation, however after updating the mod I seem to see some oddness as the animation for the flowing water for streams may not be there anymore. 

Can you confirm if it is either the issue of API+Streams, or my own issue? Or entirely other. I can't really figure this one out properly.

**Comment by embeddedt** [comment] 2022-03-20 01:22
I can confirm this behavior with just Streams, Farseek, MixinBootstrap, and Fluidlogged API installed. When Fluidlogged API is removed the blocks do flow correctly.

Here is a world that can be used to reproduce the issue quickly.

[Streams_API.zip](https://github.com/jbredwards/Fluidlogged-API/files/8310449/Streams_API.zip)

**Comment by Rongmario** [comment] 2022-03-20 02:28
IIRC Streams has two water blocks, one of them is akin to Minecraft's water, and the other is more of a dummy block, that could be the issue.

**Comment by jbredwards** [comment] 2022-03-20 02:36
The issue is caused by my renderer using the wrong flowing vec [here](https://github.com/jbredwards/Fluidlogged-API/blob/1.12.2-v1.7-Rewrite/src/main/java/git/jbredwards/fluidlogged_api/mod/asm/mixins/vanilla/block/MixinBlockLiquid.java#L212), rather than the one provided by the Streams mod [here](https://github.com/delvr/Streams/blob/1.12/src/main/scala/streams/block/BlockRiver.scala#L77)

**Comment by jbredwards** [comment] 2022-03-22 03:42
fixed in v1.7.1

**Closed as completed by jbredwards** 2022-03-22 03:42 UTC
Labels: bug, incompatibility
