### ISSUE TITLE
[rewrite] Breaking blocks underwater creates minecraft:flowing_water blocks 

### ISSUE THREAD

**Issue by embeddedt** [jbredwards/Fluidlogged-API#47] opened 2022-03-13 18:38 UTC
It seems that with Fluidlogged API 1.7 installed, breaking blocks underwater creates `minecraft:flowing_water` blocks in their place, at least on the bottom level. Below is a screenshot. The stone blocks represent the blocks I would break. It seems to be specifically the bottom back two blocks that are affected the most.

I noticed this because my item floating logic, which relies on `isInsideOfMaterial(Material.WATER)` started not working in this position, likely due to the "height" of the fluid being lower than a full block?

![2022-03-13_14 35 17](https://user-images.githubusercontent.com/42941056/158074106-9f088868-f459-43cd-8eca-59bc6e0c8194.png)

![2022-03-13_14 37 59](https://user-images.githubusercontent.com/42941056/158074189-0f4af385-16b6-476a-9d5c-878333672184.png)

**Comment by jbredwards** [comment] 2022-03-13 20:34
> It seems that with Fluidlogged API 1.7 installed, breaking blocks underwater creates minecraft:flowing_water blocks in their place

This is intentional, this mod should have any vanilla `BlockLiquidStatic` blocks the world immediately converted to their `BlockLiquidDynamic` counterparts, for more consistency. Vanilla has these two classes to reduce unnecessary block updates. One thing this mod does is replace the vanilla fluid logic with forge's, which has its own ways of handling unnecessary block updates, and doesn't need the two block system as a result.

I tested the situation, and noticed that I swam slower upward when next to other blocks. I'll fix that, I don't like it very much lol. `Entity.isInsideOfMaterial(Material.WATER)` doesn't care which of the two fluid blocks the entity's in, so perhaps the item's downward motion is fighting its newly applied upward motion, and that's why it isn't moving to the surface?

**Comment by embeddedt** [comment] 2022-03-13 20:39
>  perhaps the item's downward motion is fighting its newly applied upward motion, and that's why it isn't moving to the surface?

This mixin works 100% correctly when Fluidlogged API is not installed (i.e. the blocks are `minecraft:water` blocks), but I can try tweaking it.

**Comment by embeddedt** [comment] 2022-03-13 20:55
I also found that `isInsideOfMaterial(Material.WATER)` sometimes returns `false` for a few ticks in this specific scenario; not sure if that's related or not. If the fluid is "flowing" down, would that create more vertical velocity than in vanilla?

**Comment by jbredwards** [comment] 2022-03-13 22:10
Recreated [`EntityItemMixin`](https://github.com/Fuzss/aquaacrobatics/blob/add/1.13-blocks/src/main/java/com/fuzs/aquaacrobatics/core/mixin/EntityItemMixin.java) to test with the latest commit, and it seems to work. Closing this for now.

> I also found that isInsideOfMaterial(Material.WATER) sometimes returns false for a few ticks in this specific scenario

huh, I'll look into this

**Closed as completed by jbredwards** 2022-03-13 22:10 UTC
Labels: enhancement

**Comment by embeddedt** [comment] 2022-03-14 01:50
I can confirm it's fixed with the newest commit. Thanks!

**Comment by jbredwards** [comment] 2022-03-17 04:02
> I also found that isInsideOfMaterial(Material.WATER) sometimes returns false

The `isInsideOfMaterial` method, when interacting with vanilla fluids, uses only the block's metadata to calculate how deep the fluid is. Apparently this mod gives the vertically flowing fluids a metadata of 7 (whereas vanilla expects them to have a metadata of 8), hence the problem. This was fixed with the past two commits, along with a bunch of other issues that were caused by this (even lighting somehow)

**Comment by embeddedt** [comment] 2022-03-18 01:22
Great! One other minor issue I found: it seems that fluids render on top of the block hitbox. I'm not sure if this is a vanilla issue or not, but I don't recall seeing it before.

![image](https://user-images.githubusercontent.com/42941056/158919443-d92ee6b3-edd2-48f2-ae32-cddce4096eb9.png)

**Comment by jbredwards** [comment] 2022-03-18 01:52
that's a vanilla issue
