### ISSUE TITLE
Random crash while flying around (again)

### ISSUE THREAD

**Issue by Shazuli** [jbredwards/Fluidlogged-API#67] opened 2022-03-24 20:53 UTC
**Describe the bug**
Flying around generating new terrain causes a crash and prevents from re-joining the world.

**To Reproduce**
Was flying around generating terrain, happened twice in succession (both causes crash on joining the world again).

**Logs**
If you have access to any logs, please link them [here](https://paste.ee/p/snFYD).

**Additional context**
Here's a [link](https://ufile.io/nip3rb8f) to the mods and their config.

**Comment by embeddedt** [comment] 2022-03-24 21:13
@jbredwards Judging by the tag I'm assuming you already found the issue, but I believe the crash occurs [here](https://github.com/jbredwards/Fluidlogged-API/blob/e17ed20b0122e7d7c9d91c25a2074b499aecc00b/src/main/java/git/jbredwards/fluidlogged_api/mod/asm/mixins/vanilla/block/MixinBlockDynamicLiquid.java#L140) and is caused by using `pos` instead of `pos.down()`.

**Comment by jbredwards** [comment] 2022-03-24 21:38
> Judging by the tag I'm assuming you already found the issue

yup lol, btw I use the tag to signify that a fix for the issue is done (not necessarily committed) & will be out next update.

edit: just updated the label to make this clearer

**Comment by jbredwards** [comment] 2022-03-25 16:21
fixed in v1.7.2

**Closed as completed by jbredwards** 2022-03-25 16:21 UTC
Labels: bug
