### ISSUE TITLE
crash with futuremc

### ISSUE THREAD

**Issue by yggdrasil75** [jbredwards/Fluidlogged-API#58] opened 2022-03-19 18:48 UTC
**Describe the bug**
when trying to start the game with this mod and futuremc (and a few others) the game will not load. crash report attached.
[crash-2022-03-19_14.32.22-client.txt](https://github.com/jbredwards/Fluidlogged-API/files/8309894/crash-2022-03-19_14.32.22-client.txt)

**To Reproduce**
install futuremc and this mod and click start

**Comment by jbredwards** [comment] 2022-03-19 19:46
duplicate of #50

**Closed as completed by jbredwards** 2022-03-19 19:46 UTC
Labels: bug, duplicate
