### ISSUE TITLE
Incompatibility with Industrial Renewal multiblock structures 1.12.2

### ISSUE THREAD

**Issue by michlbro** [jbredwards/Fluidlogged-API#162] opened 2023-04-02 17:44 UTC
**Describe the bug**
Unable to place certain multiblock structures using industrial renewal version: 1.12.2-0.21.8.

**To Reproduce**
1. Add fluid logged and latest industrial renewal mod (https://www.curseforge.com/minecraft/mc-mods/industrial-renewal) in mod folder
2. Place Storage Chest/Crate from industrial renewal

**Expected behavior**
Ability to place these multiblock structures

**Logs**
https://gist.github.com/michlbro/23b32d563f0f6ded01cab3747ae951d8

**Additional context**
Industrial Renewal for 1.12.2 is no longer updated (Ported to 1.16+) so hopefully it can be solved in this mod.

**Comment by jbredwards** [comment] 2023-05-17 19:04
fixed in v2.2.0

**Closed as completed by jbredwards** 2023-05-17 19:04 UTC
Labels: bug, incompatibility

**Comment by Zafaranec** [comment] 2023-05-20 01:53
why I getting crash in startup with this new version?
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Industrial Renewal (industrialrenewal)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    cassiokf/industrialrenewal/blocks/railroad/BlockCargoLoader.func_176196_c(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)Z @56: invokevirtual
  Reason:
    Type 'net/minecraft/world/World' (current frame, stack[1]) is not assignable to 'net/minecraft/util/math/BlockPos'
  Current Frame:
    bci: @56
    flags: { }
    locals: { 'cassiokf/industrialrenewal/blocks/railroad/BlockCargoLoader', 'net/minecraft/world/World', 'net/minecraft/util/math/BlockPos', 'net/minecraft/entity/player/EntityPlayer' }
    stack: { 'cassiokf/industrialrenewal/blocks/railroad/BlockCargoLoader', 'net/minecraft/world/World', integer }
  Bytecode:
    0x0000000: 2b2c b600 5987 2cb6 005c 872c b600 5f87
    0x0000010: 1400 ee03 b600 f34e 2dc7 0005 03ac 2b2c
    0x0000020: b800 f99a 0005 03ac 2a2c b600 bfb8 00f9
    0x0000030: 9a00 0503 ac2a 2b05 b600 20b8 00f9 9a00
    0x0000040: 0503 ac2a 2b2c 05b6 0020 b600 fab6 0024
    0x0000050: b800 f99a 0005 03ac 2a2b 2cb6 00fa b600
    0x0000060: 24b8 00f9 ac                           
  Stackmap Table:
    append_frame(@30,Object[#97])
    same_frame(@40)
    same_frame(@53)
    same_frame(@67)
    same_frame(@88)

    at cassiokf.industrialrenewal.init.ModBlocks.<clinit>(ModBlocks.java:151)
    at cassiokf.industrialrenewal.init.RenderHandler.registerCustomMeshesAndStates(RenderHandler.java:31)
    at cassiokf.industrialrenewal.proxy.ClientProxy.preInit(ClientProxy.java:37)
    at cassiokf.industrialrenewal.IndustrialRenewal.preInit(IndustrialRenewal.java:52)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3601)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by jbredwards** [comment] 2023-05-20 17:24
fixed in v2.2.2 😅

**Comment by Zafaranec** [comment] 2023-05-20 17:27
thanks, for my interest, you overloading some method from Industrial Renewal that caused this or...?
