### ISSUE TITLE
Crash with The Twilight Forest's manual

### ISSUE THREAD

**Issue by LUEZISS** [jbredwards/Fluidlogged-API#201] opened 2024-05-18 21:31 UTC
Game crashes, when player is trying to view building a portal entry

**To Reproduce**
1. Start a new game
2. Get yoursself a TF guide book
3. Try to view the first quest
4. Fail

**Expected behavior**
Game crashes on older Curseforge build and freezes on the most recent Modrinth build. It should show clear instructions, how to build a proper portal. It may be, that the water involvment in the whole building process may cause some troubles.

**Comment by jbredwards** [comment] 2024-05-18 21:39
duplicate of https://github.com/jbredwards/Fluidlogged-API/issues/186

**Closed as completed by jbredwards** 2024-05-18 21:39 UTC
Labels: bug, incompatibility
