### ISSUE TITLE
1 Timestop Mod Incompat and 2 Supports of Blocks and Doors in next version.

### ISSUE THREAD

**Issue by Titoo8899** [jbredwards/Fluidlogged-API#29] opened 2021-07-23 18:18 UTC
Hi,
I have a Bug found with the Anvil then I place it on water. The Texture of this side was very uncool. I hope the Picture Help to fix the Problem. I have a link with all Mods what I have active in this time. In the link was my Mods with what I have play in this time. I hope it help to find a fix.
Link: https://drive.google.com/file/d/18000Zs6OOKnln3RYVpn0vWbWOBcaLM8H/view?usp=sharing
Photo 1:
![2021-07-23_20 06 36](https://user-images.githubusercontent.com/42325138/126823817-5246e5b2-0dca-4d98-a1f1-c14cf5f905b6.png)

The other think is. Can you a Support for the Enchantment Table and the Enderportalframes make in next Version and a Support for Doors in the next version. See the 2 other Picture what I have make. Picture 2 show the thirst 2 Blocks what I hope you can support this to your mod and the second Picture show a Door what I hope you support in the future.

Photo 2+3
![2021-07-23_20 06 54](https://user-images.githubusercontent.com/42325138/126823953-479d1bd5-79e4-4034-bc5c-71aae63df758.png)
![2021-07-23_20 07 30](https://user-images.githubusercontent.com/42325138/126823966-72a2a7b1-4b3c-48f9-adb7-c8478b1878cc.png)

**Comment by jbredwards** [comment] 2021-07-23 22:09
I probably won't add default fluidlogged support for doors, since they can't be fluidlogged in vanilla 1.13+. I want the default fluidloggable blocks to be as consistent with vanilla as possible. Someone else a while back requested fluidloggable tile entities. Here was my response: 

> -No tile entities can be fluidlogged because of how I implemented the mechanic (look at the source code to see more about this). Other mods can make their tile entities fluidloggable with some extra work, however I won't make vanilla ones fluidloggable, as doing so would require me to rewrite all of their classes, which would break tons of mods.

I'll test your issue with your mod list later today. I think this issue directly connected with your particle issue. Some questions about this issue, does the missing texture also happen when a block is waterlogged by the surface, and does the missing texture appear when fluidlogging a block with modded fluids? Just working through some ideas.

**Comment by Titoo8899** [comment] 2021-07-24 13:01
![2021-07-24_14 58 16](https://user-images.githubusercontent.com/42325138/126869197-51e5229b-89e7-4c12-b713-a95ca8d510b0.png)
Hi, this Photo show the Anvil in a normal world and on top have I water place. And then you show it give no Texture Bugs. The Bug is only then you place the Anvil under Water.

**Comment by jbredwards** [comment] 2021-07-24 14:51
After testing your modpack, the issue isn't anvils. One of the mods you have installed conflicts with mine, and removes the water model & texture from waterlogged blocks. Will be fixed next update.

**Comment by jbredwards** [comment] 2021-08-01 04:42
fixed in v1.6!

**Closed as completed by jbredwards** 2021-08-01 04:42 UTC
Labels: bug, incompatibility
