### ISSUE TITLE
ViveCraft support

### ISSUE THREAD

**Issue by TheMobC** [jbredwards/Fluidlogged-API#188] opened 2023-10-03 02:11 UTC
**When I startup the game with FluidLogged 2.2.4 it crashes with Exit code 1**
I tried a lot of other mods and they all work. I only have issues with this mod

**To Reproduce**
1. Start and launch Minecraft with Vivecraft 1.12.2 
2. crashes

**Comment by xJon** [comment] 2023-10-03 18:55
You should use the latest version (`2.2.7`) from https://modrinth.com/mod/fluidlogged-api/versions, although I'm not sure if it resolves your issue.

**Comment by TheMobC** [comment] 2023-10-03 19:52
mhmm still doesn't startup, exit code 1 again

**Comment by TheMobC** [comment] 2023-10-03 19:52
didn't mean to close it sorry

**Comment by InuYasha86000** [comment] 2023-10-08 18:27
here is the error that pops up with vivecraft, it's at the end of the log
[latest.log](https://github.com/jbredwards/Fluidlogged-API/files/12841418/latest.log)

**Comment by jbredwards** [comment] 2023-10-10 15:18
The issue is that vivecraft ships with an outdated version of optifine (fluidlogged api doesn't support F5). [This vivecraft fork](https://github.com/zurgeg/Vivecraft_112) looks like it updates the optifine version to G5, but the ideal solution would be for vivecraft to remove optifine due to how many compatibility issues it has (even compatibility issues with performance mods better than optifine).

I'm closing this since it would be more beneficial overall for vivecraft to remove optifine than for me to add compatibility with F5. This issue was also created on the vivecraft issue tracker, linking it here in case a fix is posted there: https://github.com/jrbudda/Vivecraft_112/issues/206.

If you want to use fluidlogged api with vivecraft in the meantime, you could try using the mentioned vivecraft fork. If that doesn't help, send the new crash log and I'll reopen this issue!

**Closed as completed by jbredwards** 2023-10-10 15:18 UTC
Labels: bug, wontfix, incompatibility
