### ISSUE TITLE
Breaking a water/fluidlogged block with a silk touch tool will cause it to drop a barrier item

### ISSUE THREAD

**Issue by GekidoLukas** [jbredwards/Fluidlogged-API#48] opened 2022-03-13 23:37 UTC
**Describe the bug**
When I used my axe enchanted with silk touch to break a spruce fence, that is water logged, it somehow dropped a barrier. This is repeatable and happens to every player on my server

**To Reproduce**
Break anything with silk touch that is waterlogged

**Expected behavior**
I expected no barrier

**Comment by jbredwards** [comment] 2022-03-13 23:48
duplicate of #42

**Closed as completed by jbredwards** 2022-03-13 23:48 UTC
Labels: bug, duplicate
