### ISSUE TITLE
crash on startup with the new whitelist feature

### ISSUE THREAD

**Issue by xemnes** [jbredwards/Fluidlogged-API#81] opened 2022-05-02 16:45 UTC
hello
so i added some chest blocks from treasure2 to the whitelist section of the config (i think im doing it right?)
https://i.imgur.com/36C6KPB.png

and i got this crash on startup, seems to be nbt related.
https://pastebin.com/SkiLcAPb

**Comment by embeddedt** [comment] 2022-05-02 16:46
The format is a bit different than that, see [here](https://www.curseforge.com/minecraft/mc-mods/fluidlogged-api?comment=106).

**Comment by xemnes** [comment] 2022-05-02 16:48
ahhh i see, wasnt aware they needed to be formated in that way. i tried the wiki like it said to in the comment but it doesnt look like its documented yet

**Comment by jbredwards** [comment] 2022-05-02 17:01
I plan on starting the wiki next week after I'm done will finals. Closing this, since it looks like a config formatting problem as embeddedt pointed out, not a bug with the mod. I'll reopen if there's still problems after the formatting is fixed

**Closed as completed by jbredwards** 2022-05-02 17:01 UTC
Labels: works as intended

**Comment by xemnes** [comment] 2022-05-02 20:32
hmm ok so it does appear to be fine now
however im not sure if its working properly
https://i.imgur.com/7sO8UNb.png

this indicates the block is fluidlogged but there is still an airpocket
is it because the block is a tile entity? seems to happen with all chests i add to the whitelist.

edit: so went to the surface to double check
https://i.imgur.com/M0vVk07.png
the block does have water but it appears the water doesnt cull its faces next to regular water

**Comment by jbredwards** [comment] 2022-05-02 21:01
My guess is that the block being fluidlogged doesn't have its side solidity coded correctly, I added a workaround in the config, turns out this is not an uncommon problem amongst mods. Add a `"canFluidFlow":true` flag to the whitelist entry to tell fluidlogged api to skip the built-in check for that block's side solidity in place for your pre-defined `canFluidFlow` value

**Comment by xemnes** [comment] 2022-05-03 00:09
ahhh thats much better, thank you!
