### ISSUE TITLE
Fluidlogged blocks don't hydrate farmland

### ISSUE THREAD

**Issue by Delfite** [jbredwards/Fluidlogged-API#124] opened 2022-11-09 20:07 UTC
**Describe the bug**
Unlike in Vanilla 1.13+, waterlogged blocks don't hydrate farmland when they're supposed to.

**To Reproduce**
1. Make a plot of farmland (Max size is a 9x9 square)
2. Make the center block any fluidlog-able block such as fences, stairs, or slabs
3. Use a water bucket on the center block where your fluidlog-able block should be

**What should've happened**
The waterlogged block should hydrate all of the farmland around it within a radius of 4 blocks over time.

**What actually happened**
The waterlogged block failed to hydrate any farmland around it regardless of distance.

**Screenshots**
![2022-11-09_13 42 00](https://user-images.githubusercontent.com/23504262/200919047-a0c2e8b6-46cb-48ee-a4a9-0e7206d939bd.png)
The farmland on the left is using a normal water source block. The farmland on the right is using a water-logged block.
The farmland on the left is hydrated, but the farmland on the right is not, despite the fact that it SHOULD be hydrated.

**Logs**
No crash has occurred, logs will not be provided.

**Additional context**
I was attempting to use water-logged slabs to hydrate the massive plots of farmland on my main survival world when, as it turns out, fluid-logged blocks with this mod don't hydrate the farmland they're near. Industrial Foregoing's Sewage also doesn't hydrate crops nor does it increase crop growth speed when used for fluid-logging.

**Comment by jbredwards** [comment] 2022-11-09 21:27
Fluidlogged blocks do hydrate farmland. The only things that would cause this bug are either: 1. another mod is changing the code farmland blocks use to check for water, or 2. another mod is replacing "minecraft:farmland" with an entirely new block with its own code (mods should never replace registry ids due to conflicts, but some mods do anyway).

Unlike 1.13, the way this mod works is through a system called `FluidStates`. This mod uses asm to change the code farmland blocks use to check for water to include `FluidStates`. Any other mod changing this code would break stuff and result in a conflict. I can pretty much always resolve mod conflicts like this, I just have to know the other mod first 😅

> No crash has occurred, logs will not be provided.

Logs should generally be provided with each issue, regardless of whether or not there's a crash (**especially if other mods are being used that aren't listed, in which case providing a log is a must if the issue is to be fixed!**). Logs provide me with valuable info like the mods used, active ASM/Mixin transformers, and any errors that may indicate some sort of conflict. Before I can fix this, please send your logs! For sharing your logs it's recommended to use [this](https://mclo.gs/) site.

**Comment by Delfite** [comment] 2022-11-22 03:19
> For sharing your logs it's recommended to use [this](https://mclo.gs/) site.

Here's the log: https://mclo.gs/6AUt6HY

**Comment by jbredwards** [comment] 2022-11-22 15:42
looks like a foamfix conflict. This will be fixed for the next update, in the meantime you can disable the change foamfix makes to farmland via its config.

**Comment by jbredwards** [comment] 2022-11-26 22:31
fixed in v1.9.0.0

**Closed as completed by jbredwards** 2022-11-26 22:31 UTC
Labels: bug, incompatibility
